const vouchers = [
  {
    store: "SEPHORA",
    discount: "15% off up to $15",
    minSpend: "$100",
    validity: "Dec 31, 2025",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Uniqlo",
    discount: "10% off",
    minSpend: "$50",
    validity: "Nov 30, 2025",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: true,
      popular: true,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "SEPHORA",
    discount: "Free gift with purchase",
    minSpend: "None",
    validity: "Jan 15, 2026",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "H&M",
    discount: "$10 off",
    minSpend: "$80",
    validity: "Feb 28, 2026",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "ZARA",
    discount: "Buy 1 Get 1 Free",
    minSpend: "None",
    validity: "Jan 15, 2026",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: false,
    },
  },
  {
    store: "Adidas",
    discount: "20% off",
    minSpend: "$150",
    validity: "Mar 31, 2026",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: true,
      cashback: true,
    },
  },
  {
    store: "Nike",
    discount: "Free shipping",
    minSpend: "$60",
    validity: "Apr 30, 2026",
    filterTags: ["Plus+", "Fashion"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Starbucks",
    discount: "Buy 2 Get 1 Free",
    minSpend: "$30",
    validity: "May 31, 2026",
    filterTags: ["Voucher", "Travel"],
    sortCriteria: {
      latest: true,
      popular: true,
      endingSoon: false,
      cashback: false,
    },
  },
  {
    store: "Starbucks",
    discount: "15% off all drinks",
    minSpend: "None",
    validity: "Jun 15, 2026",
    filterTags: ["Voucher", "Travel"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Apple",
    discount: "$50 off",
    minSpend: "$500",
    validity: "Jun 30, 2026",
    filterTags: ["Payments", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: false,
      endingSoon: true,
      cashback: true,
    },
  },
  {
    store: "Apple",
    discount: "5% cashback",
    minSpend: "$400",
    validity: "Jul 31, 2026",
    filterTags: ["Payments", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Samsung",
    discount: "10% cashback",
    minSpend: "$300",
    validity: "Jul 15, 2026",
    filterTags: ["Voucher", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: false,
      endingSoon: true,
      cashback: true,
    },
  },
  {
    store: "Samsung",
    discount: "Buy 1 Get 1 Free",
    minSpend: "None",
    validity: "Aug 31, 2026",
    filterTags: ["Voucher", "Travel"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: false,
      cashback: false,
    },
  },
  {
    store: "Nike",
    discount: "15% off on shoes",
    minSpend: "$70",
    validity: "Sep 15, 2026",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "H&M",
    discount: "Extra 5% off clearance",
    minSpend: "None",
    validity: "Oct 10, 2026",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: false,
      cashback: false,
    },
  },
  {
    store: "Uniqlo",
    discount: "Free shipping on orders over $40",
    minSpend: "$40",
    validity: "Nov 15, 2026",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: true,
      popular: true,
      endingSoon: false,
      cashback: false,
    },
  },
  {
    store: "ZARA",
    discount: "Extra 10% off sale items",
    minSpend: "None",
    validity: "Dec 01, 2026",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Adidas",
    discount: "Free personalized embroidery",
    minSpend: "$120",
    validity: "Dec 31, 2026",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Nike",
    discount: "Buy 2, Get 1 Free",
    minSpend: "$100",
    validity: "Jan 15, 2027",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: true,
      popular: true,
      endingSoon: false,
      cashback: false,
    },
  },
  {
    store: "Starbucks",
    discount: "20% off pastries",
    minSpend: "None",
    validity: "Feb 28, 2027",
    filterTags: ["Voucher", "Travel"],
    sortCriteria: {
      latest: false,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Apple",
    discount: "Free AirPods with select purchases",
    minSpend: "$1200",
    validity: "Mar 31, 2027",
    filterTags: ["Payments", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Samsung",
    discount: "Up to $300 trade-in bonus",
    minSpend: "$800",
    validity: "Apr 30, 2027",
    filterTags: ["Voucher", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: false,
    },
  },
  {
    store: "H&M",
    discount: "15% off new arrivals",
    minSpend: "$60",
    validity: "May 31, 2027",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Uniqlo",
    discount: "Free tote bag with purchases over $50",
    minSpend: "$50",
    validity: "Jun 15, 2027",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: true,
      popular: true,
      endingSoon: false,
      cashback: false,
    },
  },
  {
    store: "ZARA",
    discount: "$20 off when you spend $200",
    minSpend: "$200",
    validity: "Jul 31, 2027",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: true,
      cashback: true,
    },
  },
  {
    store: "Adidas",
    discount: "10% off exclusive collections",
    minSpend: "$150",
    validity: "Aug 15, 2027",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Nike",
    discount: "$15 off for members",
    minSpend: "$75",
    validity: "Sep 30, 2027",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: true,
      popular: true,
      endingSoon: false,
      cashback: false,
    },
  },
  {
    store: "Starbucks",
    discount: "Double rewards points",
    minSpend: "None",
    validity: "Oct 31, 2027",
    filterTags: ["Voucher", "Travel"],
    sortCriteria: {
      latest: false,
      popular: false,
      endingSoon: true,
      cashback: true,
    },
  },
  {
    store: "Apple",
    discount: "$100 off iPads",
    minSpend: "$500",
    validity: "Nov 30, 2027",
    filterTags: ["Payments", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: true,
      endingSoon: false,
      cashback: false,
    },
  },
  {
    store: "Samsung",
    discount: "Free extended warranty",
    minSpend: "$300",
    validity: "Dec 31, 2027",
    filterTags: ["Voucher", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: false,
    },
  },
  {
    store: "Gap",
    discount: "20% off",
    minSpend: "$100",
    validity: "Jan 31, 2028",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Old Navy",
    discount: "15% off",
    minSpend: "$75",
    validity: "Feb 28, 2028",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Banana Republic",
    discount: "Buy 1 Get 1 50% off",
    minSpend: "None",
    validity: "Mar 31, 2028",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Athleta",
    discount: "10% off",
    minSpend: "$50",
    validity: "Apr 30, 2028",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Lululemon",
    discount: "Free shipping",
    minSpend: "$100",
    validity: "May 31, 2028",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Under Armour",
    discount: "15% off",
    minSpend: "$75",
    validity: "Jun 30, 2028",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Reebok",
    discount: "20% off",
    minSpend: "$100",
    validity: "Jul 31, 2028",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Puma",
    discount: "Buy 2 Get 1 Free",
    minSpend: "$150",
    validity: "Aug 31, 2028",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "New Balance",
    discount: "10% off",
    minSpend: "$50",
    validity: "Sep 30, 2028",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Columbia",
    discount: "Free gift with purchase",
    minSpend: "$100",
    validity: "Oct 31, 2028",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Levi's",
    discount: "25% off",
    minSpend: "$100",
    validity: "Nov 30, 2028",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Gap",
    discount: "Buy 1 Get 1 50% off",
    minSpend: "None",
    validity: "Dec 31, 2028",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Old Navy",
    discount: "20% off",
    minSpend: "$75",
    validity: "Jan 31, 2029",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Banana Republic",
    discount: "15% off",
    minSpend: "$50",
    validity: "Feb 28, 2029",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Athleta",
    discount: "Buy 1 Get 1 Free",
    minSpend: "None",
    validity: "Mar 31, 2029",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Lululemon",
    discount: "10% off",
    minSpend: "$100",
    validity: "Apr 30, 2029",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Banana Republic",
    discount: "15% off",
    minSpend: "$50",
    validity: "Feb 28, 2029",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Athleta",
    discount: "Buy 1 Get 1 Free",
    minSpend: "None",
    validity: "Mar 31, 2029",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Lululemon",
    discount: "10% off",
    minSpend: "$100",
    validity: "Apr 30, 2029",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Under Armour",
    discount: "Free shipping",
    minSpend: "$75",
    validity: "May 31, 2029",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Reebok",
    discount: "15% off",
    minSpend: "$100",
    validity: "Jun 30, 2029",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Puma",
    discount: "20% off",
    minSpend: "$150",
    validity: "Jul 31, 2029",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "New Balance",
    discount: "Buy 2 Get 1 Free",
    minSpend: "$50",
    validity: "Aug 31, 2029",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Columbia",
    discount: "10% off",
    minSpend: "$100",
    validity: "Sep 30, 2029",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "North Face",
    discount: "Free gift with purchase",
    minSpend: "$150",
    validity: "Oct 31, 2029",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Patagonia",
    discount: "25% off",
    minSpend: "$200",
    validity: "Nov 30, 2029",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Arc'teryx",
    discount: "Buy 1 Get 1 50% off",
    minSpend: "None",
    validity: "Dec 31, 2029",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Marmot",
    discount: "20% off",
    minSpend: "$75",
    validity: "Jan 31, 2030",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Mountain Hardwear",
    discount: "15% off",
    minSpend: "$50",
    validity: "Feb 28, 2030",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Black Diamond",
    discount: "Buy 1 Get 1 Free",
    minSpend: "None",
    validity: "Mar 31, 2030",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "REI",
    discount: "10% off",
    minSpend: "$100",
    validity: "Apr 30, 2030",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Eddie Bauer",
    discount: "Free shipping",
    minSpend: "$75",
    validity: "May 31, 2030",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Timberland",
    discount: "15% off",
    minSpend: "$100",
    validity: "Jun 30, 2030",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Converse",
    discount: "Buy 1 Get 1 50% off",
    minSpend: "None",
    validity: "Jul 31, 2030",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Vans",
    discount: "20% off",
    minSpend: "$75",
    validity: "Aug 31, 2030",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Timberland",
    discount: "Free gift with purchase",
    minSpend: "$150",
    validity: "Sep 30, 2030",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Converse",
    discount: "10% off",
    minSpend: "$50",
    validity: "Oct 31, 2030",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Vans",
    discount: "Free shipping",
    minSpend: "$100",
    validity: "Nov 30, 2030",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Timberland",
    discount: "25% off",
    minSpend: "$200",
    validity: "Dec 31, 2030",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Converse",
    discount: "15% off",
    minSpend: "$75",
    validity: "Jan 31, 2031",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Vans",
    discount: "Buy 1 Get 1 Free",
    minSpend: "None",
    validity: "Feb 28, 2031",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Timberland",
    discount: "10% off",
    minSpend: "$50",
    validity: "Mar 31, 2031",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Converse",
    discount: "Free shipping",
    minSpend: "$100",
    validity: "Apr 30, 2031",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Vans",
    discount: "20% off",
    minSpend: "$75",
    validity: "May 31, 2031",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Timberland",
    discount: "Free gift with purchase",
    minSpend: "$150",
    validity: "Jun 30, 2031",
    filterTags: ["Fashion", "Voucher"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
  {
    store: "Converse",
    discount: "10% off",
    minSpend: "$50",
    validity: "Jul 31, 2031",
    filterTags: ["Fashion", "Plus+"],
    sortCriteria: {
      latest: true,
      popular: false,
      endingSoon: true,
      cashback: false,
    },
  },
  {
    store: "Vans",
    discount: "Free shipping",
    minSpend: "$100",
    validity: "Aug 31, 2031",
    filterTags: ["Fashion", "Travel"],
    sortCriteria: {
      latest: false,
      popular: true,
      endingSoon: false,
      cashback: true,
    },
  },
];

const updatedVouchers = vouchers.map((voucher, i) => ({
  ...voucher,
  createdAt: (i % 4) + 1,
}));

export default updatedVouchers;
